/**
 * Exercise 2.2 - Binary Trajectory Analysis Program
 * 
 * This program reads the binary trajectory file generated by the simulation
 * and computes statistical summaries of rocket trajectories.
 * 
 * Usage: gcc -o analyze_trails analyze_trails.c -lm
 *        ./analyze_trails rocket_trails.bin
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int main(int argc, char *argv[]) {
    const char *filename = "rocket_trails.bin";
    
    if (argc > 1) {
        filename = argv[1];
    }
    
    FILE *f = fopen(filename, "rb");
    if (!f) {
        printf("Error: Could not open %s\n", filename);
        return 1;
    }
    
    printf("====================================\n");
    printf("Rocket Trajectory Analysis\n");
    printf("====================================\n");
    printf("Reading from: %s\n\n", filename);
    
    // Read number of rockets
    int n_rockets;
    if (fread(&n_rockets, sizeof(int), 1, f) != 1) {
        printf("Error reading number of rockets\n");
        fclose(f);
        return 1;
    }
    
    printf("Number of rockets: %d\n\n", n_rockets);
    
    // Analyze each rocket
    for (int i = 0; i < n_rockets; i++) {
        int trail_length;
        if (fread(&trail_length, sizeof(int), 1, f) != 1) {
            printf("Error reading trail length for rocket %d\n", i);
            break;
        }
        
        // Allocate memory for trajectory
        double *trail_x = (double *)malloc(trail_length * sizeof(double));
        double *trail_y = (double *)malloc(trail_length * sizeof(double));
        
        if (!trail_x || !trail_y) {
            printf("Memory allocation failed\n");
            break;
        }
        
        // Read trajectory data
        if (fread(trail_x, sizeof(double), trail_length, f) != trail_length ||
            fread(trail_y, sizeof(double), trail_length, f) != trail_length) {
            printf("Error reading trajectory data for rocket %d\n", i);
            free(trail_x);
            free(trail_y);
            break;
        }
        
        // Compute statistics
        printf("Rocket %d:\n", i);
        printf("  Trail points: %d\n", trail_length);
        
        // Initial and final positions
        printf("  Initial position: (%.3f, %.3f)\n", trail_x[0], trail_y[0]);
        printf("  Final position: (%.3f, %.3f)\n", 
               trail_x[trail_length-1], trail_y[trail_length-1]);
        
        // Total trajectory length
        double total_length = 0.0;
        for (int j = 1; j < trail_length; j++) {
            double dx = trail_x[j] - trail_x[j-1];
            double dy = trail_y[j] - trail_y[j-1];
            total_length += sqrt(dx * dx + dy * dy);
        }
        printf("  Total trajectory length: %.3f\n", total_length);
        
        // Distance from origin (min, max, final)
        double min_dist = 1e9, max_dist = 0.0;
        for (int j = 0; j < trail_length; j++) {
            double dist = sqrt(trail_x[j] * trail_x[j] + 
                             trail_y[j] * trail_y[j]);
            if (dist < min_dist) min_dist = dist;
            if (dist > max_dist) max_dist = dist;
        }
        
        double final_dist = sqrt(trail_x[trail_length-1] * trail_x[trail_length-1] +
                                trail_y[trail_length-1] * trail_y[trail_length-1]);
        
        printf("  Distance from origin:\n");
        printf("    Minimum: %.3f\n", min_dist);
        printf("    Maximum: %.3f\n", max_dist);
        printf("    Final: %.3f\n", final_dist);
        
        // Bounding box
        double min_x = trail_x[0], max_x = trail_x[0];
        double min_y = trail_y[0], max_y = trail_y[0];
        
        for (int j = 1; j < trail_length; j++) {
            if (trail_x[j] < min_x) min_x = trail_x[j];
            if (trail_x[j] > max_x) max_x = trail_x[j];
            if (trail_y[j] < min_y) min_y = trail_y[j];
            if (trail_y[j] > max_y) max_y = trail_y[j];
        }
        
        printf("  Bounding box: X[%.3f, %.3f], Y[%.3f, %.3f]\n",
               min_x, max_x, min_y, max_y);
        
        printf("\n");
        
        // Clean up
        free(trail_x);
        free(trail_y);
    }
    
    fclose(f);
    
    printf("====================================\n");
    printf("Analysis complete!\n");
    printf("====================================\n");
    
    return 0;
}